backstage:
  ingress:
    enabled: false

  backstage:
    replicas: 1

    image:
      registry: ""
      repository: my-backstage-app
      tag: latest
      pullPolicy: IfNotPresent

    extraEnvVarsSecrets:
      - backstage-argocd-token

    extraVolumes:
      - name: backstage-argocd-ui-patch
        configMap:
          name: backstage-argocd-ui-patch

    extraVolumeMounts:
      - name: backstage-argocd-ui-patch
        mountPath: /app/packages/app/dist/static/main.31f6b62e.js
        subPath: main.31f6b62e.js
        readOnly: true
      - name: backstage-argocd-ui-patch
        mountPath: /app/packages/app/dist/static/9453.3262c7e3.chunk.js
        subPath: 9453.3262c7e3.chunk.js
        readOnly: true

    extraAppConfig:
      - filename: app-config.kind.yaml
        configMapRef: backstage-app-config

  postgresql:
    enabled: true
    image:
      registry: docker.io
      repository: bitnamilegacy/postgresql
      tag: 15.4.0-debian-11-r45
    auth:
      username: backstage
      password: backstage
      database: backstage

  extraDeploy:
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: backstage-app-config
      data:
        app-config.kind.yaml: |
          app:
            title: Backstage
            baseUrl: http://localhost:7007

          backend:
            baseUrl: http://localhost:7007
            listen:
              port: 7007
              host: 0.0.0.0
            cors:
              origin: http://localhost:7007
              methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
              credentials: true
            reading:
              allow:
                - host: raw.githubusercontent.com

          auth:
            environment: development
            dangerouslyDisableDefaultAuthPolicy: true
            providers:
              guest:
                dangerouslyAllowOutsideDevelopment: true

          catalog:
            rules:
              - allow: [Component, System, API, Resource, Location, User, Group]
            locations:
              - type: url
                target: https://raw.githubusercontent.com/roilagziel12345/DEVOPS-BACKSTAGE/9f08bf9f2d653213ec521af9b9c16966a44d53e3/catalog-info.yaml
                rules:
                  - allow: [Component, User]

          argocd:
            baseUrl: https://argocd-server.argocd.svc.cluster.local

          jenkins:
            instances:
              - name: default
                baseUrl: http://jenkins.jenkins.svc.cluster.local:8080
                username: backstage
                apiKey: local-kind-placeholder

          proxy:
            endpoints:
              '/argocd/api':
                target: https://argocd-server.argocd.svc.cluster.local/api/v1/
                changeOrigin: true
                secure: false
                headers:
                  Authorization: Bearer ${ARGOCD_AUTH_TOKEN}
