apiVersion: v1
kind: ConfigMap
metadata:
  name: backstage-argocd-ui-patch
  labels:
    app.kubernetes.io/name: backstage-argocd-ui-patch
    app.kubernetes.io/part-of: backstage
data:
  main.31f6b62e.js: |
{{ .Files.Get "files/main.31f6b62e.js" | nindent 4 }}
  9453.3262c7e3.chunk.js: |
{{ .Files.Get "files/9453.3262c7e3.chunk.js" | nindent 4 }}
